language: python
python:
- 2.6
- 2.7
install:
- python setup.py develop
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- python setup.py test
deploy:
  provider: pypi
  user: balanced-butler
  password:
    secure: jH1XW+hl+KInnde014cvX8mH5ZRiqXsxMRflR2DEs/na5mK/1LFzFt2iwgN9XwkkmXJYLPr6LA3pSLqHTMKXs8RrHaM1uXmEckXL48jcy0YkQ0+2Cl0EKcbmS8OnqIcjY3g5xFBbsFPjuRx6uJYFksJ3QatTuxkDcY/hQOc6IZg=
  on:
    tags: true
